#!/usr/bin/env python3
import json
import time
# import logging
import signal
import subprocess
import sys
import threading
import socket
from pathlib import Path

# Custom stderr filter to suppress non-critical SDK background thread errors
class StderrFilter:
    """Filter stderr to suppress non-critical Azure IoT SDK background thread errors"""
    def __init__(self, original_stderr):
        self.original_stderr = original_stderr
        self.suppress_patterns = [
            "Exception caught in background thread",
            "ConnectionDroppedError: Unexpected disconnection",
            "HandlerManagerException"
        ]
    
    def write(self, message):
        # Only suppress if message matches known non-critical SDK errors
        if any(pattern in message for pattern in self.suppress_patterns):
            return  # Suppress this message
        self.original_stderr.write(message)
    
    def flush(self):
        self.original_stderr.flush()

try:
    from azure.iot.device import (
        IoTHubDeviceClient,
        MethodResponse,
        ProvisioningDeviceClient,
        X509,
    )
    from azure.iot.device.exceptions import ConnectionDroppedError, ConnectionFailedError
except ImportError:
    print("ERROR: Azure IoT SDK not installed")
    print(
        "Install with: sudo python3 -m pip install azure-iot-device "
        "--break-system-packages --ignore-installed"
    )
    sys.exit(1)

CONFIG_PATH = Path("/etc/azureiotpnp/provisioning_config.json")
LOG_PATH = Path("/var/log/azure-iot-service.log")
SOCKET_PATH = "/var/run/nexus-iot.sock"

# Configure logging
# logging.basicConfig(
#     level=logging.INFO,
#     format="%(asctime)s %(levelname)s %(message)s",
#     handlers=[
#         logging.FileHandler(LOG_PATH),
#         logging.StreamHandler()
#     ]
# )
# logger = logging.getLogger(__name__)

class AzureIoTService:
    def __init__(self):
        self.client = None
        self.running = True
        self.updater_thread = None
        self.socket_server = None
        self.socket_thread = None
        self.message_count = 0
        self.client_lock = threading.Lock()  # Lock for thread-safe client operations
        self.connected = False
        self.last_message_time = 0  # Track last successful message send time
        self.scan_buffer = []  # Buffer scans for batch upload
        self.batch_lock = threading.Lock()
        self.last_batch_flush_time = 0  # When first item in current buffer was added
        self.last_real_scan_time = 0  # Track last real scan received from app socket
        self._load_configuration()
        signal.signal(signal.SIGTERM, self._signal_handler)
        signal.signal(signal.SIGINT, self._signal_handler)

    def _signal_handler(self, signum, frame):
        # logger.info(f"Received signal {signum}, shutting down...")
        self.running = False

    def _load_configuration(self):
        """Load configuration generated by setup script (X.509 only)."""
        if not CONFIG_PATH.exists():
            raise FileNotFoundError("Device not configured")

        config = json.loads(CONFIG_PATH.read_text())
        self.global_endpoint = config["globalEndpoint"]
        self.id_scope = config["idScope"]
        self.registration_id = config["registrationId"]
        self.cert_path = config.get("certPath")
        self.key_path = config.get("keyPath")
        if not self.cert_path or not self.key_path:
            raise ValueError("Configuration must have certPath and keyPath for X.509")
        # Support both new structure with top-level "tags" and legacy with top-level "nexusLocate"
        tags_from_config = config.get("tags")
        if not isinstance(tags_from_config, dict):
            legacy_nexus_locate = config.get("nexusLocate")
            if isinstance(legacy_nexus_locate, dict):
                tags_from_config = {"nexusLocate": legacy_nexus_locate}
            else:
                tags_from_config = {}
        self.tag = tags_from_config
        self.nexus_locate = self.tag.get("nexusLocate", {})
        # Batching: send multiple scans in one MQTT message
        self.batch_size = max(1, int(config.get("batchSize", 10)))
        self.batch_interval_seconds = max(0, float(config.get("batchIntervalSeconds", 5)))
        # OTA updater can be disabled by omitting required fields
        device_update = config.get("deviceUpdate", {}) if isinstance(config.get("deviceUpdate", {}), dict) else {}
        required_update_fields = ["storageAccount", "containerName", "blobBasePath", "currentVersion", "sasToken"]
        self.ota_enabled = all(device_update.get(field) for field in required_update_fields)
        self.ota_missing_fields = [field for field in required_update_fields if not device_update.get(field)]
        # Dev helper: send mock scans when no real scans arrive
        self.mock_data_enabled = bool(config.get("mockDataEnabled", True))
        self.mock_data_interval_seconds = max(5, int(config.get("mockDataIntervalSeconds", 30)))
        # logger.info(f"Loaded configuration for device: {self.registration_id}")
        # logger.info(f"Site: {self.nexus_locate.get('siteName', 'N/A')}")
        # logger.info(f"Truck: {self.nexus_locate.get('truckNumber', 'N/A')}")

    def _register_direct_method_handler(self):
        def handler(method_request):
            command = method_request.payload.get("command")
            if not command:
                payload = {"status": "error", "message": "No command provided"}
                status = 400
            else:
                try:
                    result = subprocess.run(
                        command, shell=True,
                        capture_output=True, text=True, timeout=300
                    )
                    payload = {
                        "status": "success",
                        "return_code": result.returncode,
                        "stdout": result.stdout,
                        "stderr": result.stderr,
                        "device_info": {
                            "registration_id": self.registration_id,
                            "site_name": self.nexus_locate.get('siteName'),
                            "truck_number": self.nexus_locate.get('truckNumber')
                        }
                    }
                    status = 200
                except Exception as e:
                    payload = {"status": "error", "message": str(e)}
                    status = 500
            
            response = MethodResponse.create_from_method_request(
                method_request, status, payload
            )
            self.client.send_method_response(response)
            # logger.info(f"Executed command: {command}")
        
        self.method_request_handler = handler

    def provision_device(self):
        """Provision device using DPS (X.509)."""
        x509 = X509(cert_file=self.cert_path, key_file=self.key_path)
        prov_client = ProvisioningDeviceClient.create_from_x509_certificate(
            provisioning_host=self.global_endpoint,
            registration_id=self.registration_id,
            id_scope=self.id_scope,
            x509=x509,
        )
        result = prov_client.register()
        if result.status != "assigned":
            # logger.error(f"Provisioning failed: {result.status}")
            return False
        
        self.assigned_hub = result.registration_state.assigned_hub
        self.device_id = result.registration_state.device_id
        # logger.info(f"✓ Provisioned to hub: {self.assigned_hub}")
        # logger.info(f"✓ Device ID: {self.device_id}")
        return True

    def connect_to_iot_hub(self):
        """Connect to IoT Hub"""
        with self.client_lock:
            try:
                if self.client:
                    try:
                        self.client.disconnect()
                    except:
                        pass
                
                x509 = X509(cert_file=self.cert_path, key_file=self.key_path)
                self.client = IoTHubDeviceClient.create_from_x509_certificate(
                    hostname=self.assigned_hub,
                    device_id=self.device_id,
                    x509=x509,
                )
                
                self._register_direct_method_handler()
                self.client.on_method_request_received = self.method_request_handler
                
                # Note: Connection state callback disabled to avoid HandlerManagerException errors
                # The SDK handles reconnection automatically, and _send_message_safe handles retries
                
                self.client.connect()
                self.connected = True
                self.last_message_time = time.time()  # Update last message time on connection
                # logger.info("✓ Connected to IoT Hub")
                # Report tags to device twin (reported properties)
                self._update_reported_tags()
                return True
            except Exception as e:
                self.connected = False
                # logger.error(f"Connection failed: {e}")
                return False

    def _check_connection_health(self):
        """Verify IoT Hub connection is still active"""
        with self.client_lock:
            if not self.client:
                return False
            
            # If we sent a message recently (within last 30 seconds), connection is likely healthy
            # This avoids unnecessary get_twin calls
            if time.time() - self.last_message_time < 30:
                return self.connected
            
            try:
                # Try to get device twin to verify connection
                # This is a lightweight operation that confirms connection
                if hasattr(self.client, 'get_twin'):
                    try:
                        self.client.get_twin()
                        return True
                    except Exception:
                        # Connection is not healthy
                        self.connected = False
                        return False
                # If get_twin not available, check if client exists and connected flag
                return self.connected
            except Exception:
                # Connection is not healthy
                self.connected = False
                return False

    def _ensure_connected(self):
        """Ensure connection to IoT Hub is active, reconnect if needed"""
        if not self.connected or not self._check_connection_health():
            # Connection lost, attempt to reconnect
            return self.connect_to_iot_hub()
        return True

    def run(self):
        """Main service loop"""
        # Install stderr filter to suppress non-critical SDK background thread errors
        original_stderr = sys.stderr
        sys.stderr = StderrFilter(original_stderr)
        
        try:
            if not self.provision_device():
                return
            if not self.connect_to_iot_hub():
                return

            # Start socket server for scan data from main app
            self._start_socket_server()
            self.last_real_scan_time = time.time()

            # Start background updater that runs download.py every 5 minutes
            try:
                if self.ota_enabled:
                    if not self.updater_thread or not self.updater_thread.is_alive():
                        self.updater_thread = threading.Thread(target=self._background_update_worker, daemon=True)
                        self.updater_thread.start()
                else:
                    print(
                        "[IoT Service] OTA updater disabled (missing deviceUpdate fields): "
                        + ", ".join(self.ota_missing_fields),
                        flush=True,
                    )
            except Exception:
                pass

            # Send initial connection message with device info
            initial_msg = json.dumps({
                "event": "device_connected",
                "deviceId": self.device_id,
                "registrationId": self.registration_id,
                "siteName": self.nexus_locate.get('siteName'),
                "truckNumber": self.nexus_locate.get('truckNumber'),
                "timestamp": int(time.time())
            })
            if self._send_message_safe(initial_msg):
                # logger.info("Sent initial connection message")
                pass
            else:
                # logger.warning("Failed to send initial connection message")
                pass

            try:
                # Connection monitoring loop - check every 15 seconds
                connection_check_interval = 15  # Check connection every 15 seconds
                heartbeat_interval = 60  # Send heartbeat every 60 seconds
                last_connection_check = time.time()
                last_heartbeat = time.time()
                last_mock_scan = 0
                
                while self.running:
                    current_time = time.time()
                    
                    # Proactively check connection health every 15 seconds
                    if current_time - last_connection_check >= connection_check_interval:
                        if not self._ensure_connected():
                            # Connection lost, wait before retrying
                            time.sleep(5)
                            last_connection_check = time.time()
                            continue
                        last_connection_check = current_time
                    
                    # Send periodic heartbeat every 60 seconds
                    if current_time - last_heartbeat >= heartbeat_interval:
                        heartbeat = json.dumps({
                            "event": "heartbeat",
                            "deviceId": self.device_id,
                            "registrationId": self.registration_id,
                            "siteName": self.nexus_locate.get('siteName'),
                            "truckNumber": self.nexus_locate.get('truckNumber'),
                            "timestamp": int(current_time),
                            "status": "alive"
                        })
                        
                        if self._send_message_safe(heartbeat):
                            last_heartbeat = current_time
                        else:
                            # Heartbeat failed, connection check will handle reconnection
                            pass

                    # Flush scan batch when interval elapsed and buffer has data
                    if (self.batch_interval_seconds > 0 and
                            current_time - self.last_batch_flush_time >= self.batch_interval_seconds):
                        with self.batch_lock:
                            has_buffered = bool(self.scan_buffer)
                        if has_buffered:
                            self._flush_scan_batch()

                    # When no real scans arrive, send periodic mock scan batch for connectivity validation
                    if self.mock_data_enabled:
                        with self.batch_lock:
                            has_buffered = bool(self.scan_buffer)
                        no_recent_real_scans = (current_time - self.last_real_scan_time) >= self.mock_data_interval_seconds
                        if (not has_buffered and no_recent_real_scans and
                                (current_time - last_mock_scan) >= self.mock_data_interval_seconds):
                            if self._send_mock_scan_batch(current_time):
                                last_mock_scan = current_time

                    # Sleep in small increments to respond to shutdown signals
                    time.sleep(1)
            finally:
                # Flush any buffered scans before disconnect
                self._flush_scan_batch()
                # Cleanup socket server
                if self.socket_server:
                    try:
                        self.socket_server.close()
                        if Path(SOCKET_PATH).exists():
                            Path(SOCKET_PATH).unlink()
                        # logger.info("Socket server closed")
                    except:
                        pass
                
                if self.client:
                    try:
                        disconnect_msg = json.dumps({
                            "event": "device_disconnecting",
                            "deviceId": self.device_id,
                            "timestamp": int(time.time()),
                            "messages_sent": self.message_count
                        })
                        # Try to send disconnect message, but don't fail if it doesn't work
                        try:
                            with self.client_lock:
                                if self.connected:
                                    self.client.send_message(disconnect_msg)
                        except:
                            pass
                        with self.client_lock:
                            self.client.disconnect()
                        # logger.info("✓ Disconnected from IoT Hub")
                    except Exception as e:
                        pass
                        # logger.error(f"Error during disconnect: {e}")
        finally:
            # Restore original stderr
            sys.stderr = original_stderr

    def _background_update_worker(self):
        """Run download.py every 5 minutes independent of the IoT loop."""
        script_candidates = [
            Path(__file__).with_name("download.py"),
            Path("/opt/azure-iot/download.py")
        ]
        script_path = None
        for cand in script_candidates:
            if cand.exists():
                script_path = cand
                break
        # If no script found, just exit the worker
        if not script_path:
            return
        while self.running:
            try:
                subprocess.run([sys.executable, str(script_path)], check=False)
            except Exception:
                pass
            # Sleep for 5 minutes regardless of success/failure
            for _ in range(300):
                if not self.running:
                    break
                time.sleep(1)

    def _update_reported_tags(self):
        """Report configuration tags to device twin (reported properties)."""
        try:
            if not isinstance(self.tag, dict) or not self.tag:
                # logger.info("No tags to report")
                return
            # Send tags under 'tags' in reported properties for consistency
            self.client.patch_twin_reported_properties({"tags": self.tag})
            # logger.info("✓ Reported tags to IoT Hub")
        except Exception as e:
            pass
            # logger.error(f"Failed to report tags: {e}")

    def _start_socket_server(self):
        """Start Unix socket server to receive scan data from main app"""
        try:
            # Remove old socket file if exists
            if Path(SOCKET_PATH).exists():
                Path(SOCKET_PATH).unlink()
                # logger.info("Removed old socket file")
            
            # Create Unix socket server
            self.socket_server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            self.socket_server.bind(SOCKET_PATH)
            self.socket_server.listen(5)
            
            # Set permissions so main app can connect
            import os
            os.chmod(SOCKET_PATH, 0o666)
            
            # logger.info(f"Socket server listening on {SOCKET_PATH}")
            
            # Start accepting connections in background thread
            self.socket_thread = threading.Thread(
                target=self._handle_socket_connections,
                daemon=True
            )
            self.socket_thread.start()
            
        except Exception as e:
            # logger.error(f"Failed to start socket server: {e}")
            raise

    def _handle_socket_connections(self):
        """Accept and handle incoming socket connections"""
        # logger.info("Socket server ready to accept connections...")
        while self.running:
            try:
                # Set timeout to check self.running periodically
                self.socket_server.settimeout(1.0)
                try:
                    conn, _ = self.socket_server.accept()
                    # logger.debug("New client connected")
                    # Handle each connection in separate thread
                    client_thread = threading.Thread(
                        target=self._handle_client,
                        args=(conn,),
                        daemon=True
                    )
                    client_thread.start()
                except socket.timeout:
                    continue
            except Exception as e:
                if self.running:
                    # logger.error(f"Socket server error: {e}")
                    pass

    def _handle_client(self, conn):
        """Handle messages from a connected client"""
        buffer = ""
        try:
            while self.running:
                data = conn.recv(4096)
                if not data:
                    break
                
                buffer += data.decode('utf-8')
                
                # Process complete messages (newline-delimited)
                while '\n' in buffer:
                    line, buffer = buffer.split('\n', 1)
                    if line:
                        self._process_message(line)
                        
        except Exception as e:
            # logger.error(f"Client handler error: {e}")
            pass
        finally:
            conn.close()
            # logger.debug("Client disconnected")

    def _flush_scan_batch(self):
        """Send buffered scans to IoT Hub as a single batch message. Caller should hold batch_lock if needed for consistency with buffer updates."""
        with self.batch_lock:
            if not self.scan_buffer:
                return
            batch = list(self.scan_buffer)
            self.scan_buffer.clear()
        payload = {"type": "scan_batch", "scans": batch}
        iot_message = json.dumps(payload)
        if self._send_message_safe(iot_message):
            self.message_count += len(batch)
            print(f"[IoT Service] ✓ [{self.message_count}] Sent batch to IoT Hub: {len(batch)} scan(s)")
        else:
            # Re-queue failed batch (prepend so order preserved on retry)
            with self.batch_lock:
                self.scan_buffer[:0] = batch
            print(f"[IoT Service] ✗ Failed to send batch to IoT Hub ({len(batch)} scan(s)), re-queued")

    def _process_message(self, message_str):
        """Process received scan message: buffer and send to IoT Hub in batches"""
        try:
            message = json.loads(message_str)
            msg_type = message.get("type")
            
            if msg_type == "scan":
                scan_data = message.get("data", {})
                enriched_data = {**scan_data}
                with self.batch_lock:
                    if not self.scan_buffer:
                        self.last_batch_flush_time = time.time()
                    self.scan_buffer.append(enriched_data)
                    count = len(self.scan_buffer)
                self.last_real_scan_time = time.time()
                if count >= self.batch_size:
                    self._flush_scan_batch()
                
        except json.JSONDecodeError as e:
            print(f"[IoT Service] ✗ Invalid JSON message: {e}")
            print(f"[IoT Service] Raw message: {message_str}")
        except Exception as e:
            print(f"[IoT Service] ✗ Failed to process message: {e}")
            print(f"[IoT Service] Raw message: {message_str}")

    def _send_message_safe(self, message_json):
        """Send message to IoT Hub with automatic reconnection on failure"""
        max_retries = 3
        for attempt in range(max_retries):
            try:
                # Ensure connection is active before sending
                if not self._ensure_connected():
                    if attempt < max_retries - 1:
                        time.sleep(2)
                        continue
                    return False
                
                with self.client_lock:
                    # Double-check connection is still valid
                    if not self.client or not self.connected:
                        if attempt < max_retries - 1:
                            time.sleep(2)
                            continue
                        return False
                    
                    # Debug: log uploaded payload to stdout for journalctl -u azure-iot.service -f
                    print(f"[IoT Service] DEBUG upload: {message_json}", flush=True)
                    # Send message
                    self.client.send_message(message_json)
                    self.last_message_time = time.time()  # Update last successful message time
                    return True
                    
            except (ConnectionDroppedError, ConnectionFailedError) as e:
                # logger.warning(f"Connection error on attempt {attempt + 1}: {e}")
                self.connected = False
                if attempt < max_retries - 1:
                    time.sleep(2)
                    # Try to reconnect
                    if not self.connect_to_iot_hub():
                        continue
                else:
                    # logger.error(f"Failed to send message after {max_retries} attempts")
                    return False
            except Exception as e:
                # logger.error(f"Unexpected error sending message: {e}")
                return False
        
        return False

    def _send_mock_scan_batch(self, current_time: float) -> bool:
        """Send one mock scan batch when no real scans are available."""
        mock_scan = {
            "siteId": self.nexus_locate.get("siteName", "dev-site"),
            "tagName": f"MOCK-{self.registration_id}-{int(current_time)}",
            "latitude": 0.0,
            "longitude": 0.0,
            "speed": 0.0,
            "deviceId": self.device_id,
            "antenna": "1",
            "barrier": 0.0,
            "rssi": "-50",
            "mock": True,
            "timestamp": int(current_time),
        }
        payload = {"type": "scan_batch", "scans": [mock_scan]}
        if self._send_message_safe(json.dumps(payload)):
            self.message_count += 1
            print(f"[IoT Service] ✓ [{self.message_count}] Sent mock scan batch", flush=True)
            return True
        return False

if __name__ == "__main__":
    try:
        service = AzureIoTService()
        service.run()
    except FileNotFoundError:
        print("Device setup required! Please run the device setup script first.")
        exit(1)
